# Site settings
title: Malaria vector genome observatory
email: data@malariagen.net
description: > 
  Explore and analyse genomic data from sewuencing of malatia mosquitoes.
baseurl: "/landing-page-creative/" # the subpath of your site, e.g. /blog/
url: "https://alimanfoo.github.io" # the base hostname & protocol for your site

twitter_username: malariagenomics
github_username: malariagen

# Build settings
markdown: kramdown
