# Site settings
title: Malaria vector genome observatory
email:
description: > Explore and analyse genomic data from whole-genome sewuencing of malatia mosquitoes. # this means to ignore newlines until "baseurl:"
baseurl: "/landing-page-creative/" # the subpath of your site, e.g. /blog/
url: "https://alimanfoo.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
